### PR TITLE
Fix #2 (broken image on home page)

### LINKED ISSUE #2: Fix broken image on home page
The "donate to ASF" image is no longer available. It'd be also nice to change the copyright statement at the bottom from 2013 to 2024.

### PR DESCRIPTION
**Pull request by DrDub**
Fix broken / old images

Changed copyright year on pages

If the changes are good to go, I'll add to this PR the generated `docs/`

### CODE REVIEW

**Comment by reckart** [comment]
I'd drop X at this point. 

Are you planning to stick to the old Velocity?

**Comment by DrDub** [comment]
Nope. Just trying to build ways to work together. Once we have this working then we can do PRs with changes to velocity, etc. and discuss them here.

**Comment by reckart** [comment]
Are you planning to go live wit this page and then gradually move it to a new foundation or is the idea to stick with the existing site until this repo here has undergone full transformation?

**Comment by DrDub** [comment]
> Are you planning to go live wit this page and then gradually move it to a new foundation or is the idea to stick with the existing site until this repo here has undergone full transformation?

Yes, I like gradual changes so we can make sure we are all in the same page (pun intended).

And... X is gone ;-)

**Comment by reckart** [comment]
I normally like gradual change as well, but if we are moving to a new site build system, that is a pretty fundamental change - and one single massive PR at that point. So I guess at least we'd have one cataclysmic change here.

But anyway, going away from Subversion is already a good step and trimming down the existing page at the same time is also good, so let's do that.

**Comment by DrDub** [comment]
Looks Good To Merge?

**Comment by reckart** [comment]
IMHO the site should be self-contained. E.g. are currently linking to an asset on S3 and community-over-code which should I think should be copied into the site proper to avoid rot if we forget to removed them in time.

Formally, we usually use the following format for commit messages in other repos:

```
Issue #NUM: Title of the issue per GitHub

- Change one
- Change two
```

I think if we switch to an issue-driven process in this repo as well, the same convention should be followed.

**Comment by DrDub** [comment]
I was planning to squash the commits here following the review. The format you describe sounds good.

I agree with the self-contained bit. Let me upload these two images and update the PR. There might be other instances of deep linking in the site. Maybe open another issue for that?

**Comment by reckart** [comment]
> There might be other instances of deep linking in the site. Maybe open another issue for that?

Maybe - or just fix them along naturally as part of other changes. I have no strong opinion here.

**Comment by DrDub** [comment]
Home page deeplink is removed. The images went into `docs/images`. `xdocs/images` actually doesn't work.

**Comment by reckart** [comment]
AFAIK `xdocs` only has the `.xml` files that are transformed via velocity. All static content (e.g. also the board reports, documentation, etc.) goes directoy to `docs`.

**Review by reckart — APPROVED** [review]

**Pull request merged**
